layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: "code.r"
   # repository: sonanmemon/sonanmemon.github.io

 #social_media:
 #  facebook: sonan ahmed
  # dribbble: your_username
   #facebook: Sonan Ahmed
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter:
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Applied Business Cycle Theory, Especially Expectation Driven and Endogenous Business Cycle Models
    #web_url: https://github.com/topics/css
    image_url: https://oregoneconomicanalysis.files.wordpress.com/2016/05/tradadv0216.png
    
  - name: Applied Monetary Economics, Especially Central Bank Institutional Design and Macroeconomic Volatility
    image_url: https://cdnuploads.aa.com.tr/uploads/Contents/2019/09/18/thumbs_b_c_6b1a931d50107d764bcaba855a28ed99.jpg?v=222511
    
  - name: Machine Learning, Especially RL and DNN's and Their Applications in Macroeconomics
    image_url: https://www.docwirenews.com/wp-content/uploads/2019/06/1_p6ahiOqtwW6mxgk-WCDvlg.jpeg
    
    
    

  

  
