layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
   # repository: sonanmemon/sonanmemon.github.io

 #social_media:
 #  facebook: sonan ahmed
  # dribbble: your_username
   #facebook: Sonan Ahmed
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter:
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Applied Business Cycle Theory, Especially Expectation Driven and Endogenous Business Cycle Models
    #web_url: https://github.com/topics/css
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
    
  - name: Applied Monetary Economics, Especially Central Bank Institutional Design and Macroeconomic Volatility
    
  - name: Machine Learning, Especially RL and DNN's and Their Applications in Macroeconomics
    
    

  

  
